if(typeof Object.create!="function")Object.create=function(q){function u(){}u.prototype=q;return new u};(function(q){q.grapher={}})(window);var hz="h";
(function(q,u){function r(a,d){h="";b=a;d.style==hz&&(a=a=="y"?"x":"y");for(x=0;x<=d[a+"units"].length-1;x++)d.style==hz?h="<li>"+d[a+"units"][x]+"</li>"+h:h+="<li>"+d[a+"units"][x]+"</li>";return'<ul class="'+b+'Axis">'+h+"</ul>"}function v(){var a=function(){return((1+Math.random())*65536|0).toString(16).substring(1)};return a()+a()+"-"+a()+"-"+a()+"-"+a()+"-"+a()+a()+a()}function t(a,d,f,c,e){e.innerHTML+='<div style="position:absolute;margin-left:'+a+"px;margin-top:"+d+"px;width:"+f+"px;height:"+
c+"px;clip:rect(0,"+f+"px,"+c+'px,0);background-color:#000;"></div>'}function m(a,d,f,c,e){if(a>f)var i=f,j=c,f=a,c=d,a=i,d=j;var i=f-a,j=Math.abs(c-d),g=d,o=d>c?-1:1;if(i>=j){for(var k=j<<1,n=k-(i<<1),l=k-i,d=a;i-- >0;)++a,l>0?(t(d,g,a-d,1,e),g+=o,l+=n,d=a):l+=k;t(d,g,f-d+1,1,e)}else if(k=i<<1,n=k-(j<<1),l=k-j,i=g,c<=d){for(;j-- >0;)l>0?(t(a++,g,1,i-g+1,e),g+=o,l+=n,i=g):(g+=o,l+=k);t(f,c,1,i-c+1,e)}else{for(;j-- >0;)g+=o,l>0?(t(a++,i,1,g-i,e),l+=n,i=g):l+=k;t(f,i,1,c-i+1,e)}}function w(a,d){return a<
d?-1:(a>d)*1}q.bar=function(a,d,f){a=u.getElementById(a);m(25,351,400,351,a);m(25,1,25,351,a);if(a){if(!f||!d)return a.innerHTML+="missing param",!1;var c=r("y",f);a.innerHTML+=c;var c=33,e=330,i="50%",j="33px",g="left",o="top",k="left",n="22px",l="height";f.style==hz&&(c=330,e=33,i="33px",j="50%",g="top",o="right",k="top",n="0px",l="width");guid="d"+v();h='<dl id="'+guid+'">';for(var p in d)if(d.hasOwnProperty(p)&&(s=d[p],s.length>1&&(s=s[0]),h+='<dd><span style="'+l+":"+s+'%;"><b>'+s+"</b></span></dd>",
d[p].length>1))for(b=1;b<d[p].length;b++)h+='<dd class="sub" ><span style="'+l+":"+d[p][b]+'%;"><b>'+d[p][b]+"</b></span></dd> ";d=h+"</dl>"+r("x",f)+"<style>ul.xAxis{float:left;clear:left;display:inline;width:454px;margin:0 0 0 27px;padding:0} ul.yAxis{display:inline;float:left;margin:14px 0 0;padding:0;height:370px;} ul.xAxis li{float:left;list-style:none;width:33px;text-align:center} ul.yAxis li{list-style:none;height:33px;text-align:right;float:left;clear:left} dl#"+guid+",dl#"+guid+" dt,dl#"+
guid+" dd{margin:0;padding:0} dl#"+guid+"{width:454px;height:360px;padding-left:11px;float:left} dl#"+guid+" dd{position:relative;display:block;float:left;width:"+c+"px;height:"+e+"px;margin-top:"+n+";} dl#"+guid+" span{position:absolute;display:block;width:"+j+";bottom:0;left:0;z-index:1;color:#555;text-decoration:none;height:"+i+";background:#456} dl#"+guid+" span b{display:block;font-weight:700;font-style:normal;float:left;line-height:200%;color:#fff;position:absolute;"+o+":5px;"+k+":3px;text-align:right;width:23px} dl#"+
guid+" .sub{margin-"+g+":-33px} dl#"+guid+" .sub span{background:#978}</style>";a.innerHTML+=d}};q.line=function(a,d,f){a=u.getElementById(a);xoffset=25;m(25,351,400,351,a);m(25,1,25,351,a);if(a){if(!f||!d)return a.innerHTML+="missing param",!1;var c=r("y",f);a.innerHTML+=c;c=[];counter=0;for(var e in d)d.hasOwnProperty(e)&&(c[counter]=[],c[counter][0]=d[e][0]+xoffset,c[counter][1]=d[e][1],counter+=1);for(e=0;e<=c.length-1;e++)c[e+1]&&m(c[e][0],c[e][1],c[e+1][0],c[e+1][1],a);d=r("x",f);a.innerHTML+=
d}};q.area=function(a,d,f){a=u.getElementById(a);xoffset=25;fillPolygon([26,25,50,80,100,150,210,325,325],[351,1,75,65,105,155,15,300,351],a);m(25,351,400,351,a);m(25,1,25,351,a);if(a){if(!f||!d)return a.innerHTML+="missing param",!1;var c=r("y",f);a.innerHTML+=c;c=[];counter=0;for(var e in d)d.hasOwnProperty(e)&&(c[counter]=[],c[counter][0]=d[e][0]+xoffset,c[counter][1]=d[e][1],counter+=1);for(e=0;e<=c.length-1;e++)c[e+1]&&m(c[e][0],c[e][1],c[e+1][0],c[e+1][1],a);d=r("x",f);a.innerHTML+=d}};q.plot=
function(a,d,f){a=u.getElementById(a);m(25,351,400,351,a);m(25,1,25,351,a);xoffset=25;if(a){if(!f||!d)return a.innerHTML+="missing param",!1;var c=r("y",f);a.innerHTML+=c;c=[];counter=0;for(var e in d)d.hasOwnProperty(e)&&(c[counter]=[],c[counter][0]=d[e][0]+xoffset,c[counter][1]=d[e][1],counter+=1);for(e=0;e<=c.length-1;e++)c[e]&&t(c[e][0],c[e][1],4,4,a);d=r("x",f);a.innerHTML+=d}};this.fillPolygon=function(a,d,f){var c,e,i,j,g,o,k,n,l,p=a.length;if(p){e=d[0];i=d[0];for(c=1;c<p;c++)d[c]<e&&(e=d[c]),
d[c]>i&&(i=d[c]);for(;e<=i;e++){var m=[];for(c=l=0;c<p;c++){c?(j=c-1,n=c):(j=p-1,n=0);g=d[j];k=d[n];if(g<k)j=a[j],o=a[n];else if(g>k)k=d[j],g=d[n],o=a[j],j=a[n];else continue;e>=g&&e<k?m[l++]=Math.round((e-g)*(o-j)/(k-g)+j):e==i&&e>g&&e<=k&&(m[l++]=Math.round((e-g)*(o-j)/(k-g)+j))}m.sort(w);for(c=0;c<l;c+=2)t(m[c],e,m[c+1]-m[c]+1,1,f)}}}})(grapher,document);